// Generated by [go-option] -type ClientOpt; DO NOT EDIT
// If you have any questions, please create issues and submit contributions at:
// https://github.com/gtkit/go-option

package cluster

import (
	"crypto/tls"
	"time"
)

type ClientOptOption interface {
	apply(*ClientOpt)
}

func NewClientOpt(opts ...ClientOptOption) *ClientOpt {
	clientOpt := &ClientOpt{}

	for _, opt := range opts {
		opt.apply(clientOpt)
	}

	return clientOpt
}

/**
 * field name: Addrs
 */
type Addrs struct {
	addrs []string
}

// apply the Addrs option to the given struct.
func (a Addrs) apply(opt *ClientOpt) {
	opt.Addrs = a.addrs
}

// WithAddrs Option.
func WithAddrs(optAddrs []string) ClientOptOption {
	return Addrs{
		addrs: optAddrs,
	}
}

/**
 * field name: MaxRedirects
 */
type MaxRedirects struct {
	maxRedirects int
}

// apply the MaxRedirects option to the given struct.
func (m MaxRedirects) apply(opt *ClientOpt) {
	opt.MaxRedirects = m.maxRedirects
}

// WithMaxRedirects Option.
func WithMaxRedirects(optMaxRedirects int) ClientOptOption {
	return MaxRedirects{
		maxRedirects: optMaxRedirects,
	}
}

/**
 * field name: Username
 */
type Username struct {
	username string
}

// apply the Username option to the given struct.
func (u Username) apply(opt *ClientOpt) {
	opt.Username = u.username
}

// WithUsername Option.
func WithUsername(optUsername string) ClientOptOption {
	return Username{
		username: optUsername,
	}
}

/**
 * field name: Password
 */
type Password struct {
	password string
}

// apply the Password option to the given struct.
func (p Password) apply(opt *ClientOpt) {
	opt.Password = p.password
}

// WithPassword Option.
func WithPassword(optPassword string) ClientOptOption {
	return Password{
		password: optPassword,
	}
}

/**
 * field name: DialTimeout
 */
type DialTimeout struct {
	dialTimeout time.Duration
}

// apply the DialTimeout option to the given struct.
func (d DialTimeout) apply(opt *ClientOpt) {
	opt.DialTimeout = d.dialTimeout
}

// WithDialTimeout Option.
func WithDialTimeout(optDialTimeout time.Duration) ClientOptOption {
	return DialTimeout{
		dialTimeout: optDialTimeout,
	}
}

/**
 * field name: ReadTimeout
 */
type ReadTimeout struct {
	readTimeout time.Duration
}

// apply the ReadTimeout option to the given struct.
func (r ReadTimeout) apply(opt *ClientOpt) {
	opt.ReadTimeout = r.readTimeout
}

// WithReadTimeout Option.
func WithReadTimeout(optReadTimeout time.Duration) ClientOptOption {
	return ReadTimeout{
		readTimeout: optReadTimeout,
	}
}

/**
 * field name: WriteTimeout
 */
type WriteTimeout struct {
	writeTimeout time.Duration
}

// apply the WriteTimeout option to the given struct.
func (w WriteTimeout) apply(opt *ClientOpt) {
	opt.WriteTimeout = w.writeTimeout
}

// WithWriteTimeout Option.
func WithWriteTimeout(optWriteTimeout time.Duration) ClientOptOption {
	return WriteTimeout{
		writeTimeout: optWriteTimeout,
	}
}

/**
 * field name: TLSConfig
 */
type TLSConfig struct {
	tLSConfig *tls.Config
}

// apply the TLSConfig option to the given struct.
func (t TLSConfig) apply(opt *ClientOpt) {
	opt.TLSConfig = t.tLSConfig
}

// WithTLSConfig Option.
func WithTLSConfig(optTLSConfig *tls.Config) ClientOptOption {
	return TLSConfig{
		tLSConfig: optTLSConfig,
	}
}
